name: Feature Request (Developers Only)
description: For developers only, please. End-users should ask a question in our Discussions Q&A for support.
title: '[Feature Request]: '
labels: [new feature/enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this new feature/enhancement request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: request
    attributes:
      label: Requested Feature/Enhancment
      description: Explicitly state what you would like too see in TSML
      placeholder: Describe specifics and alternatives
      value: 'Please add this cool feature!'
    validations:
      required: true
  - type: dropdown
    id: tsmlVersion
    attributes:
      label: TSML Version
      description: What version of TSML are you running?
      options:
        - Latest (default)
        - beta
        - Other (Identify version in text above)
    validations:
      required: true
  - type: dropdown
    id: wordperssVersion
    attributes:
      label: Wordpress Version
      description: What version of Wordpress is on the site?
      options:
        - Latest (default)
        - Other (Identify version in text above)
    validations:
      required: true
      render: shell
